<a href="https://colab.research.google.com/github/venkateshblks/Neural-networks/blob/main/Neural_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

## Data Exploration and Preprocessing

In [4]:
data=pd.read_csv('Alphabets_data.csv')
data

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          T     2     8      3       5      1     8    13      0      6   
1          I     5    12      3       7      2    10     5      5      4   
2          D     4    11      6       8      6    10     6      2      6   
3          N     7    11      6       6      3     5     9      4      6   
4          G     2     1      3       1      1     8     6      6      6   
...      ...   ...   ...    ...     ...    ...   ...   ...    ...    ...   
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0          6      10       8      0       8      0       8  
1         13       3       9      2       8      4      10  
2         10       3       7      3       7      3       9  
3          4       4      10      6      10      2       8  
4          6       5       9      1       7      5      10  
...      ...     ...     ...    ...     ...    ...     ...  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8  

[20000 rows x 17 columns]

In [ ]:
data.letter.value_counts().reindex(sorted(data.letter.value_counts().index))

letter
A    789
B    766
C    736
D    805
E    768
F    775
G    773
H    734
I    755
J    747
K    739
L    761
M    792
N    783
O    753
P    803
Q    783
R    758
S    748
T    796
U    813
V    764
W    752
X    787
Y    786
Z    734
Name: count, dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64 
 2   ybox    20000 non-null  int64 
 3   width   20000 non-null  int64 
 4   height  20000 non-null  int64 
 5   onpix   20000 non-null  int64 
 6   xbar    20000 non-null  int64 
 7   ybar    20000 non-null  int64 
 8   x2bar   20000 non-null  int64 
 9   y2bar   20000 non-null  int64 
 10  xybar   20000 non-null  int64 
 11  x2ybar  20000 non-null  int64 
 12  xy2bar  20000 non-null  int64 
 13  xedge   20000 non-null  int64 
 14  xedgey  20000 non-null  int64 
 15  yedge   20000 non-null  int64 
 16  yedgex  20000 non-null  int64 
dtypes: int64(16), object(1)
memory usage: 2.6+ MB


In [ ]:
data.isna().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [ ]:
data.describe()

xbox          ybox         width       height         onpix  \
count  20000.000000  20000.000000  20000.000000  20000.00000  20000.000000   
mean       4.023550      7.035500      5.121850      5.37245      3.505850   
std        1.913212      3.304555      2.014573      2.26139      2.190458   
min        0.000000      0.000000      0.000000      0.00000      0.000000   
25%        3.000000      5.000000      4.000000      4.00000      2.000000   
50%        4.000000      7.000000      5.000000      6.00000      3.000000   
75%        5.000000      9.000000      6.000000      7.00000      5.000000   
max       15.000000     15.000000     15.000000     15.00000     15.000000   

               xbar          ybar         x2bar         y2bar         xybar  \
count  20000.000000  20000.000000  20000.000000  20000.000000  20000.000000   
mean       6.897600      7.500450      4.628600      5.178650      8.282050   
std        2.026035      2.325354      2.699968      2.380823      2.488475   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        6.000000      6.000000      3.000000      4.000000      7.000000   
50%        7.000000      7.000000      4.000000      5.000000      8.000000   
75%        8.000000      9.000000      6.000000      7.000000     10.000000   
max       15.000000     15.000000     15.000000     15.000000     15.000000   

            x2ybar        xy2bar         xedge        xedgey         yedge  \
count  20000.00000  20000.000000  20000.000000  20000.000000  20000.000000   
mean       6.45400      7.929000      3.046100      8.338850      3.691750   
std        2.63107      2.080619      2.332541      1.546722      2.567073   
min        0.00000      0.000000      0.000000      0.000000      0.000000   
25%        5.00000      7.000000      1.000000      8.000000      2.000000   
50%        6.00000      8.000000      3.000000      8.000000      3.000000   
75%        8.00000      9.000000      4.000000      9.000000      5.000000   
max       15.00000     15.000000     15.000000     15.000000     15.000000   

            yedgex  
count  20000.00000  
mean       7.80120  
std        1.61747  
min        0.00000  
25%        7.00000  
50%        8.00000  
75%        9.00000  
max       15.00000

In [ ]:
data.columns

Index(['letter', 'xbox', 'ybox', 'width', 'height', 'onpix', 'xbar', 'ybar',
       'x2bar', 'y2bar', 'xybar', 'x2ybar', 'xy2bar', 'xedge', 'xedgey',
       'yedge', 'yedgex'],
      dtype='object')

In [5]:
X = data.drop('letter', axis=1)
y = data['letter']
X.head()

xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  x2ybar  \
0     2     8      3       5      1     8    13      0      6      6      10   
1     5    12      3       7      2    10     5      5      4     13       3   
2     4    11      6       8      6    10     6      2      6     10       3   
3     7    11      6       6      3     5     9      4      6      4       4   
4     2     1      3       1      1     8     6      6      6      6       5   

   xy2bar  xedge  xedgey  yedge  yedgex  
0       8      0       8      0       8  
1       9      2       8      4      10  
2       7      3       7      3       9  
3      10      6      10      2       8  
4       9      1       7      5      10

## Model Implementation

In [6]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,classification_report
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test,y_train , y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_train

5894     E
3728     E
8958     N
7671     K
5999     V
        ..
11284    G
11964    Z
5390     X
860      I
15795    J
Name: letter, Length: 16000, dtype: object

In [ ]:
model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=100, random_state=42,n_jobs=-1)

model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(max_iter=100, random_state=42)

In [ ]:
y_pred = model.predict(X_test)
y_pred

array(['Z', 'L', 'A', ..., 'Q', 'Y', 'Y'], dtype='<U1')

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.91      0.93      0.92       149
           B       0.76      0.82      0.79       153
           C       0.93      0.73      0.82       137
           D       0.72      0.90      0.80       156
           E       0.79      0.87      0.83       141
           F       0.87      0.87      0.87       140
           G       0.82      0.87      0.84       160
           H       0.82      0.69      0.75       144
           I       0.92      0.86      0.89       146
           J       0.91      0.85      0.88       149
           K       0.83      0.74      0.78       130
           L       0.94      0.85      0.89       155
           M       0.93      0.95      0.94       168
           N       0.98      0.87      0.92       151
           O       0.83      0.83      0.83       145
           P       0.93      0.85      0.89       173
           Q       0.95      0.84      0.89       166
           R       0.75    

## Hyperparameter Tuning

In [ ]:
param_grid = {
    'hidden_layer_sizes': [(50,), (100,)],
    'activation': ['relu', 'tanh'],
    'learning_rate_init': [ 0.01, 0.1]
}

grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=MLPClassifier(max_iter=100, random_state=42),
             n_jobs=-1,
             param_grid={'activation': ['relu', 'tanh'],
                         'hidden_layer_sizes': [(50,), (100,)],
                         'learning_rate_init': [0.01, 0.1]},
             scoring='accuracy')

In [ ]:
best_params = grid_search.best_params_
best_params

{'activation': 'tanh',
 'hidden_layer_sizes': (100,),
 'learning_rate_init': 0.01}

In [ ]:
best_model=tuned_model = grid_search.best_estimator_
best_model

MLPClassifier(activation='tanh', learning_rate_init=0.01, max_iter=100,
              random_state=42)

In [ ]:
best_model.fit(X_train, y_train)
y_pred_tuned = tuned_model.predict(X_test)
y_pred_tuned

array(['X', 'L', 'A', ..., 'Q', 'Y', 'Y'], dtype='<U1')

In [ ]:
print(classification_report(y_test, y_pred_tuned))

              precision    recall  f1-score   support

           A       0.94      0.99      0.97       149
           B       0.86      0.90      0.88       153
           C       0.87      0.89      0.88       137
           D       0.91      0.88      0.89       156
           E       0.91      0.88      0.89       141
           F       0.84      0.94      0.89       140
           G       0.84      0.91      0.87       160
           H       0.84      0.79      0.81       144
           I       0.96      0.91      0.93       146
           J       0.91      0.95      0.93       149
           K       0.86      0.87      0.86       130
           L       0.98      0.93      0.95       155
           M       0.96      0.99      0.97       168
           N       0.95      0.94      0.94       151
           O       0.91      0.90      0.91       145
           P       0.99      0.90      0.94       173
           Q       0.98      0.90      0.94       166
           R       0.88    

## Evaluation

In [ ]:
print("The default model's accuracy:", accuracy_score(y_test, y_pred))
print("The tuned model's accuracy:", accuracy_score(y_test, y_pred_tuned))

The default model's accuracy: 0.863
The tuned model's accuracy: 0.9165


In [ ]:
print("The default model's precision:", precision_score(y_test, y_pred, average='weighted'))
print("The tuned model's precision:", precision_score(y_test, y_pred_tuned, average='weighted'))
print("The default model's recall:", recall_score(y_test, y_pred, average='weighted'))
print("The tuned model's recall:", recall_score(y_test, y_pred_tuned, average='weighted'))
print("The default model's F1 Score:", f1_score(y_test, y_pred, average='weighted'))
print("The tuned model's F1 Score:", f1_score(y_test, y_pred_tuned, average='weighted'))

The default model's precision: 0.8687629298571423
The tuned model's precision: 0.9185324925775588
The default model's recall: 0.863
The tuned model's recall: 0.9165
The default model's F1 Score: 0.8634897901376672
The tuned model's F1 Score: 0.9166751623546748


In [ ]:
print(classification_report(y_test, y_pred))   #The default model

              precision    recall  f1-score   support

           A       0.91      0.93      0.92       149
           B       0.76      0.82      0.79       153
           C       0.93      0.73      0.82       137
           D       0.72      0.90      0.80       156
           E       0.79      0.87      0.83       141
           F       0.87      0.87      0.87       140
           G       0.82      0.87      0.84       160
           H       0.82      0.69      0.75       144
           I       0.92      0.86      0.89       146
           J       0.91      0.85      0.88       149
           K       0.83      0.74      0.78       130
           L       0.94      0.85      0.89       155
           M       0.93      0.95      0.94       168
           N       0.98      0.87      0.92       151
           O       0.83      0.83      0.83       145
           P       0.93      0.85      0.89       173
           Q       0.95      0.84      0.89       166
           R       0.75    

In [ ]:
print(classification_report(y_test, y_pred_tuned))  #the tuned model

              precision    recall  f1-score   support

           A       0.94      0.99      0.97       149
           B       0.86      0.90      0.88       153
           C       0.87      0.89      0.88       137
           D       0.91      0.88      0.89       156
           E       0.91      0.88      0.89       141
           F       0.84      0.94      0.89       140
           G       0.84      0.91      0.87       160
           H       0.84      0.79      0.81       144
           I       0.96      0.91      0.93       146
           J       0.91      0.95      0.93       149
           K       0.86      0.87      0.86       130
           L       0.98      0.93      0.95       155
           M       0.96      0.99      0.97       168
           N       0.95      0.94      0.94       151
           O       0.91      0.90      0.91       145
           P       0.99      0.90      0.94       173
           Q       0.98      0.90      0.94       166
           R       0.88    

**Hyperparameter tuning helped improve the model's performance across all metrics.**

**By carefully selecting the optimal combination of hyperparameters, the tuned model achieved higher accuracy, precision, recall, and F1-score compared to the default model.**



---

\

---



## Using Tensorflow

In [7]:
import tensorflow as tf


In [8]:
from sklearn.preprocessing import LabelEncoder
l= LabelEncoder()
y_en = l.fit_transform(y)
y_en

array([19,  8,  3, ..., 19, 18,  0])

In [9]:
X_train, X_test,y_train , y_test = train_test_split(X, y_en, test_size=0.2, random_state=42)
y_train

array([ 4,  4, 13, ..., 23,  8,  9])

In [10]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(90, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(26, activation='softmax')
])

optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=15, batch_size=32, verbose=0)

In [11]:
y_pred = model.predict(X_test)
y_pred

125/125 [==============================] - 0s 2ms/step


array([[2.39377164e-11, 8.89523921e-09, 1.02346842e-12, ...,
        4.50683106e-03, 2.80483647e-07, 9.92142797e-01],
       [6.23352546e-03, 5.30078588e-03, 4.38681804e-03, ...,
        9.04991478e-03, 7.33764202e-04, 6.57565602e-09],
       [9.99999940e-01, 2.04411626e-23, 9.58391268e-15, ...,
        4.97844952e-21, 3.83299946e-21, 9.32283306e-17],
       ...,
       [4.35077908e-07, 1.25207326e-13, 1.91270804e-03, ...,
        3.93134283e-13, 8.12743631e-14, 4.56149875e-13],
       [2.71640439e-02, 1.10609221e-07, 1.01634284e-13, ...,
        1.47555652e-03, 9.40367758e-01, 3.87765205e-04],
       [5.66322459e-15, 1.10698994e-26, 5.00442130e-21, ...,
        1.58426092e-10, 9.99996126e-01, 1.73089727e-25]], dtype=float32)

In [14]:
y_pred1 = np.argmax(y_pred, axis=1)
y_pred1

array([25, 11,  0, ..., 14, 24, 24])

In [15]:
accuracy_score(y_test, y_pred1)

0.83

In [16]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.87      0.93      0.90       149
           1       0.69      0.86      0.76       153
           2       0.86      0.77      0.82       137
           3       0.65      0.89      0.75       156
           4       0.78      0.77      0.78       141
           5       0.90      0.73      0.81       140
           6       0.64      0.92      0.76       160
           7       0.77      0.67      0.72       144
           8       0.95      0.85      0.90       146
           9       0.87      0.89      0.88       149
          10       0.88      0.65      0.75       130
          11       0.97      0.84      0.90       155
          12       0.96      0.90      0.93       168
          13       0.90      0.83      0.87       151
          14       0.69      0.87      0.77       145
          15       0.86      0.90      0.88       173
          16       0.85      0.78      0.81       166
          17       0.75    